CREATE TABLE IF EXISTS Dentista (id INT PRIMARY KEY AUTO_INCREMENT, nome VARCHAR(100) NOT NULL,
sobrenome VARCHAR(100) NOT NULL, matricula VARCHAR(100) NOT NULL);

CREATE TABLE IF EXISTS Paciente (id INT PRIMARY KEY AUTO_INCREMENT, nome VARCHAR(100) NOT NULL,
sobrenome VARCHAR(100) NOT NULL, rg VARCHAR(13) NOT NULL, data_registro VARCHAR(50) NOT NULL, id_endereco INT NOT NULL,
);

CREATE TABLE IF EXISTS Endereco (id INT PRIMARY KEY AUTO_INCREMENT, rua VARCHAR(50) NOT NULL, numero INT NOT NULL,
cidade VARCHAR(50) NOT NULL, sigla_estado VARCHAR(50) NOT NULL);

CREATE TABLE IF EXISTS Consulta (id INT PRIMARY KEY AUTO_INCREMENT, id_paciente INT NOT NULL, id_dentista INT NOT NULL,
data_consulta DATETIME NOT NULL);