CREATE TABLE IF NOT EXISTS Dentista (id INT PRIMARY KEY AUTO_INCREMENT, nome VARCHAR(100) NOT NULL,
sobrenome VARCHAR(100) NOT NULL, matricula VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS Paciente (id INT PRIMARY KEY AUTO_INCREMENT, nome VARCHAR(100) NOT NULL,
sobrenome VARCHAR(100) NOT NULL, rg VARCHAR(13) NOT NULL, data_registro VARCHAR(50) NOT NULL, id_endereco INT NOT NULL,
FOREIGN KEY (id_endereco) REFERENCES Endereco(id));

CREATE TABLE IF NOT EXISTS Endereco (id INT PRIMARY KEY AUTO_INCREMENT, rua VARCHAR(50) NOT NULL, numero INT NOT NULL,
cidade VARCHAR(50) NOT NULL, sigla_estado VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS Consulta (id INT PRIMARY KEY AUTO_INCREMENT, id_paciente INT NOT NULL, id_dentista INT NOT NULL,
data_consulta DATETIME NOT NULL, FOREIGN KEY (id_paciente) REFERENCES paciente(id), FOREIGN KEY (id_dentista) REFERENCES dentista(id));